/* this file is auto-generated by setup.py */
extern RenderPrimitiveInterface primitive_base;
extern RenderPrimitiveInterface primitive_cave;
extern RenderPrimitiveInterface primitive_clear_base;
extern RenderPrimitiveInterface primitive_depth_tinting;
extern RenderPrimitiveInterface primitive_depth;
extern RenderPrimitiveInterface primitive_edge_lines;
extern RenderPrimitiveInterface primitive_exposed;
extern RenderPrimitiveInterface primitive_height_fading;
extern RenderPrimitiveInterface primitive_hide;
extern RenderPrimitiveInterface primitive_lighting;
extern RenderPrimitiveInterface primitive_nether;
extern RenderPrimitiveInterface primitive_nether_old;
extern RenderPrimitiveInterface primitive_no_fluids;
extern RenderPrimitiveInterface primitive_overlay_biomes;
extern RenderPrimitiveInterface primitive_overlay_mineral;
extern RenderPrimitiveInterface primitive_overlay_slime;
extern RenderPrimitiveInterface primitive_overlay_spawn;
extern RenderPrimitiveInterface primitive_overlay;
extern RenderPrimitiveInterface primitive_smooth_lighting;
static RenderPrimitiveInterface *render_primitives[] = {
    &primitive_base,
    &primitive_cave,
    &primitive_clear_base,
    &primitive_depth_tinting,
    &primitive_depth,
    &primitive_edge_lines,
    &primitive_exposed,
    &primitive_height_fading,
    &primitive_hide,
    &primitive_lighting,
    &primitive_nether,
    &primitive_nether_old,
    &primitive_no_fluids,
    &primitive_overlay_biomes,
    &primitive_overlay_mineral,
    &primitive_overlay_slime,
    &primitive_overlay_spawn,
    &primitive_overlay,
    &primitive_smooth_lighting,
    NULL
};
